package com.example.paperclipper.auth

import android.content.Context
import android.content.Intent
import com.example.paperclipper.R
import com.example.paperclipper.util.Logx
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow

/**
 * Firebase + Google Sign-In wrapper.
 *
 * SCAFFOLD: fully wired, but inert until Firebase is configured. Sign-in is "configured" only when
 * [R.string.firebase_web_client_id] is set AND a default FirebaseApp exists (i.e. the
 * `com.google.gms.google-services` plugin + google-services.json have been added). Every Firebase
 * call is guarded so the app never crashes while unconfigured.
 */
class AuthManager(private val context: Context) {

    private val _email = MutableStateFlow(currentEmailOrNull())
    val email: StateFlow<String?> = _email

    private val _displayName = MutableStateFlow(currentNameOrNull())
    val displayName: StateFlow<String?> = _displayName

    /** Last sign-in error message (for surfacing to the user); null when none. */
    private val _signInError = MutableStateFlow<String?>(null)
    val signInError: StateFlow<String?> = _signInError

    fun clearSignInError() { _signInError.value = null }

    private fun auth(): FirebaseAuth? = runCatching { FirebaseAuth.getInstance() }.getOrNull()

    private fun webClientId(): String {
        // Prefer the OAuth web client id generated by the google-services plugin (present once
        // google-services.json is added); fall back to the manually-set placeholder string.
        // Resolved by name to avoid a compile-time dependency on the generated resource.
        val generated = context.resources.getIdentifier(
            "default_web_client_id", "string", context.packageName,
        )
        if (generated != 0) return context.getString(generated)
        return context.getString(R.string.firebase_web_client_id)
    }

    fun isConfigured(): Boolean = webClientId().isNotBlank() && auth() != null

    private fun currentEmailOrNull(): String? = auth()?.currentUser?.email
    private fun currentNameOrNull(): String? = auth()?.currentUser?.displayName

    private fun client(): GoogleSignInClient {
        val options = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(webClientId())
            .requestEmail()
            .build()
        return GoogleSignIn.getClient(context, options)
    }

    /** Intent to start the Google chooser, or null if sign-in isn't configured yet. */
    fun signInIntent(): Intent? {
        if (!isConfigured()) {
            Logx.w(TAG, "signInIntent: not configured (firebaseApp=${auth() != null}, webClientIdBlank=${webClientId().isBlank()})")
            return null
        }
        return client().signInIntent
    }

    /** Completes sign-in from the chooser result by exchanging the Google id token with Firebase. */
    fun handleSignInResult(data: Intent?) {
        _signInError.value = null
        val account = try {
            GoogleSignIn.getSignedInAccountFromIntent(data).getResult(ApiException::class.java)
        } catch (e: ApiException) {
            Logx.w(TAG, "Google sign-in failed: statusCode=${e.statusCode}")
            _signInError.value = "Google sign-in failed (code ${e.statusCode})"
            return
        }
        val idToken = account.idToken
        if (idToken == null) {
            Logx.w(TAG, "Google account has no id token (web client id misconfigured?)")
            _signInError.value = "No ID token from Google (check web client id)"
            return
        }
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        auth()?.signInWithCredential(credential)?.addOnCompleteListener { task ->
            if (task.isSuccessful) {
                _email.value = auth()?.currentUser?.email
                _displayName.value = auth()?.currentUser?.displayName
                Logx.i(TAG, "Firebase sign-in OK: ${Logx.redactEmail(_email.value)}")
            } else {
                Logx.w(TAG, "Firebase signInWithCredential failed", task.exception)
                _signInError.value = "Firebase sign-in failed: ${task.exception?.message}"
            }
        }
    }

    private companion object { const val TAG = "PaperAuth" }

    fun signOut() {
        runCatching { auth()?.signOut() }
        runCatching { client().signOut() }
        _email.value = null
        _displayName.value = null
    }
}
